# Curated India (NSE) universe — Nifty 100-ish, yfinance .NS suffix.
# No free bulk API exists for NSE/BSE constituents (unofficial scrapers like
# nsepython exist but are fragile). Hand-maintained; review periodically
# against nseindia.com's index constituent pages.

INDIA_NSE_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "BAJFINANCE.NS",
    "KOTAKBANK.NS", "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "WIPRO.NS",
    "ADANIENT.NS", "ADANIPORTS.NS", "BAJAJFINSV.NS", "HCLTECH.NS", "M&M.NS",
    "NTPC.NS", "POWERGRID.NS", "TATAMOTORS.NS", "TATASTEEL.NS", "JSWSTEEL.NS",
    "ONGC.NS", "COALINDIA.NS", "GRASIM.NS", "TECHM.NS", "INDUSINDBK.NS",
    "HINDALCO.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "EICHERMOT.NS",
    "BRITANNIA.NS", "APOLLOHOSP.NS", "BPCL.NS", "HEROMOTOCO.NS", "SBILIFE.NS",
    "HDFCLIFE.NS", "BAJAJ-AUTO.NS", "SHREECEM.NS", "UPL.NS", "TATACONSUM.NS",
    "GODREJCP.NS", "DABUR.NS", "PIDILITIND.NS", "SIEMENS.NS", "DLF.NS",
    "HAVELLS.NS", "AMBUJACEM.NS", "BANKBARODA.NS", "PNB.NS", "CANBK.NS",
    "IOC.NS", "GAIL.NS", "VEDL.NS", "SAIL.NS", "BEL.NS", "HAL.NS",
    "BOSCHLTD.NS", "MARICO.NS", "COLPAL.NS", "MUTHOOTFIN.NS", "CHOLAFIN.NS",
    "LUPIN.NS", "AUROPHARMA.NS", "TORNTPHARM.NS", "BIOCON.NS", "PAGEIND.NS",
    "TRENT.NS", "NAUKRI.NS", "PIIND.NS", "SRF.NS", "ICICIPRULI.NS",
    "ICICIGI.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "TATAPOWER.NS", "ZOMATO.NS",
]
